version: "3"
services:
  covid-api:
    image: covid-api
    container_name: covid-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"